### ISSUE TITLE
The links for the weights seems to be broken

### ISSUE THREAD

**Issue by nagyt2** [Abhishek97M/Handgun-Detection-Deepstream#2]
Both links to the weights file on Google Drive seems to be broken.

**Comment by Abhishek97M** [comment]
I am so sorry , The weights folder on the GDrive seems to be deleted somehow ,I will be uploading the weights soon .

**Comment by Abhishek97M** [comment]
Hi @nagyt2 , I have added a new Google drive link  for yolov3 weights.

Thanks.
